In [2]:
import numpy as np

numpy_val : np.ndarray = np.array('5000')

display(f"object : {numpy_val}")
display(f"object shape : {numpy_val.shape}")
display(f"object dtype : {numpy_val.dtype}")
display(f"object type : {type(numpy_val)}")
display(f"object ndim : {numpy_val.ndim}")
display(f"object size : {numpy_val.size}")
display(f"object itemsize : {numpy_val.itemsize}")

'object : 5000'

'object shape : ()'

'object dtype : <U4'

"object type : <class 'numpy.ndarray'>"

'object ndim : 0'

'object size : 1'

'object itemsize : 16'

In [5]:
import numpy as np

numpy_val : np.ndarray = np.array(['a','c','hello','no where','fast'])

display(f"object : {numpy_val}")
display(f"object shape : {numpy_val.shape}")
display(f"object dtype : {numpy_val.dtype}")
display(f"object type : {type(numpy_val)}")
display(f"object ndim : {numpy_val.ndim}")
display(f"object size : {numpy_val.size}")
display(f"object itemsize : {numpy_val.itemsize}")

"object : ['a' 'c' 'hello' 'no where' 'fast']"

'object shape : (5,)'

'object dtype : <U8'

"object type : <class 'numpy.ndarray'>"

'object ndim : 1'

'object size : 5'

'object itemsize : 32'

In [2]:
import numpy as np

numpy_val : np.ndarray = np.array([1,2,3,4,5,6,100,1222,13424])

display(f"object : {numpy_val}")
display(f"object shape : {numpy_val.shape}")
display(f"object dtype : {numpy_val.dtype}")
display(f"object type : {type(numpy_val)}")
display(f"object ndim : {numpy_val.ndim}")
display(f"object size : {numpy_val.size}")
display(f"object itemsize : {numpy_val.itemsize}")

'object : [    1     2     3     4     5     6   100  1222 13424]'

'object shape : (9,)'

'object dtype : int64'

"object type : <class 'numpy.ndarray'>"

'object ndim : 1'

'object size : 9'

'object itemsize : 8'

In [7]:
import numpy as np

numpy_val : np.ndarray = np.array([[1,2,1,4],[1,1,3,4],[4,7,8,9]])

display(f"object : {numpy_val}")
display(f"object shape : {numpy_val.shape}")
display(f"object dtype : {numpy_val.dtype}")
display(f"object type : {type(numpy_val)}")
display(f"object ndim : {numpy_val.ndim}")
display(f"object size : {numpy_val.size}")
display(f"object itemsize : {numpy_val.itemsize}")

'object : [[1 2 1 4]\n [1 1 3 4]\n [4 7 8 9]]'

'object shape : (3, 4)'

'object dtype : int64'

"object type : <class 'numpy.ndarray'>"

'object ndim : 2'

'object size : 12'

'object itemsize : 8'

In [8]:
import numpy as np

numpy_val : np.ndarray = np.array([[[1,2,9],[1,4,88]],[[1,1,0],[3,4,4]],[[1,1,0],[3,4,4]]])

display(f"object : {numpy_val}")
display(f"object shape : {numpy_val.shape}")
display(f"object dtype : {numpy_val.dtype}")
display(f"object type : {type(numpy_val)}")
display(f"object ndim : {numpy_val.ndim}")
display(f"object size : {numpy_val.size}")
display(f"object itemsize : {numpy_val.itemsize}")

'object : [[[ 1  2  9]\n  [ 1  4 88]]\n\n [[ 1  1  0]\n  [ 3  4  4]]\n\n [[ 1  1  0]\n  [ 3  4  4]]]'

'object shape : (3, 2, 3)'

'object dtype : int64'

"object type : <class 'numpy.ndarray'>"

'object ndim : 3'

'object size : 18'

'object itemsize : 8'

In [ ]:
data = np.arange(11)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
data = np.arange(1,11,2)
data

array([1, 3, 5, 7, 9])

In [11]:
data = np.arange(1,5)
data + 5

array([6, 7, 8, 9])

In [ ]:
list1 = [1,3,7,9]
list1
# list1 + 5 # error

CPU times: total: 0 ns
Wall time: 0 ns


[1, 3, 7, 9]

In [ ]:
list1 = [1,3,7,9]
[i+2 for i in list1]

CPU times: total: 0 ns
Wall time: 0 ns


[3, 5, 9, 11]

In [32]:
%%time

num1 = list(range(1, 10000000))


CPU times: total: 422 ms
Wall time: 647 ms


In [33]:
%%time
import numpy as np

num1 = np.arange(1,10000000)

CPU times: total: 156 ms
Wall time: 302 ms


In [41]:
ndata = np.arange(1,20)
print(ndata)
print(ndata[:4])
print(ndata[0:4])
print(ndata[6:13])
print( ndata[6:10] )

print(ndata)

ndata[6:10] = 4

print(ndata)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2 3 4]
[1 2 3 4]
[ 7  8  9 10 11 12 13]
[ 7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  2  3  4  5  6  4  4  4  4 11 12 13 14 15 16 17 18 19]


In [4]:
state_bank = np.array([1,4,6,7,13])
unl_bank = np.random.randint(1,50,20)

display(state_bank)
display(unl_bank)

array([ 1,  4,  6,  7, 13])

array([11,  9,  8, 25, 11, 43,  8, 13, 41, 21, 20, 46, 30,  8, 41,  9, 18,
       24, 14,  6], dtype=int32)

In [5]:
select = np.array([True,False,True,False,False])

In [74]:
state_bank[select]

array([1, 6])

In [75]:
state_bank[1]

np.int64(4)

In [76]:
state_bank % 2 != 0
# state_bank % 2 == 0

array([ True, False, False,  True,  True])

In [ ]:
# state_bank[state_bank % 2 != 0]
# state_bank[state_bank % 2 == 0]
# state_bank[False]
state_bank[True]

array([[ 1,  4,  6,  7, 13]])

In [ ]:

display(state_bank)
display(unl_bank)

np.isin(unl_bank,state_bank) # bool value

array([ 1,  4,  6,  7, 13])

array([11,  9,  8, 25, 11, 43,  8, 13, 41, 21, 20, 46, 30,  8, 41,  9, 18,
       24, 14,  6], dtype=int32)

array([False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False,  True])

In [ ]:

display(state_bank)
display(unl_bank)

np.isin(state_bank,unl_bank)  # bool value


array([ 1,  4,  6,  7, 13])

array([11,  9,  8, 25, 11, 43,  8, 13, 41, 21, 20, 46, 30,  8, 41,  9, 18,
       24, 14,  6], dtype=int32)

array([False, False,  True, False,  True])

In [119]:

display(state_bank)
display(unl_bank)

state_bank[np.isin(state_bank,unl_bank)]

array([ 1,  4,  6,  7, 13])

array([14,  7, 20, 38, 28, 21, 35, 43, 44, 38, 16,  3, 40, 34, 40,  1, 27,
       30, 48, 32], dtype=int32)

array([1, 7])

In [121]:
np.intersect1d(state_bank,unl_bank)

array([1, 7])

In [123]:
np.intersect1d(unl_bank,state_bank)

array([1, 7])

In [ ]:
np.where(state_bank > unl_bank,state_bank,unl_bank) # both array should be of same rowns and column i.e same dimension and size

ValueError: operands could not be broadcast together with shapes (5,) (20,) 

In [15]:
x = np.random.randint(1,100,20)
y = np.random.randint(1,100,20)

# z = np.where(x > y , x, "less") # gives x if x > y and less if y > x
z1 = np.where(x > y , x, 0) # gives x if x > y and gives 0 if y > x
z2 = np.where(x > y , x, y) # gives x if x > y and gives y if y > x

display(x)
display(y)

display(z1)
display(z2)


array([ 3,  8, 37, 49, 50,  1, 68, 22, 26, 18, 33, 74, 74,  1,  2, 79, 83,
       24, 27, 92], dtype=int32)

array([31, 52, 59, 45, 84, 15, 45, 93, 48, 32, 86, 56, 18, 22, 75,  1, 31,
       93, 48, 12], dtype=int32)

array([ 0,  0,  0, 49,  0,  0, 68,  0,  0,  0,  0, 74, 74,  0,  0, 79, 83,
        0,  0, 92], dtype=int32)

array([31, 52, 59, 49, 84, 15, 68, 93, 48, 32, 86, 74, 74, 22, 75, 79, 83,
       93, 48, 92], dtype=int32)

In [149]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([['d','f'],['m','n']])
c = np.array([['B'],['A']])
d = np.array(['Z','Y'])

print(a)
print(b)
print(c)
print(d)

[[1 2 3]
 [4 5 6]]
[['d' 'f']
 ['m' 'n']]
[['B']
 ['A']]
['Z' 'Y']


In [163]:
a = np.arange(3*3).reshape(3,3)
display(a)

b = np.arange(5*3).reshape(5,3)
display(b)

c = np.arange(3*5).reshape(3,5)
display(c)

d = np.arange(5*3).reshape(3,5)
display(d)

e = np.arange(3*5).reshape(5,3)
display(e)



array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [183]:
x = np.arange(3*3*4).reshape(3,3,4) 
display(x)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [20]:
data = np.random.randint(1,21,(5,10))
data

array([[ 3, 12,  4, 16,  9, 10, 17, 19,  2, 14],
       [20,  7, 20, 10, 12,  3, 13, 13, 11,  8],
       [17, 16, 10, 15, 15,  3, 10,  3,  2, 12],
       [14,  8,  9,  7, 20,  3,  6, 15, 12,  6],
       [ 2, 18,  3, 19,  7, 18, 16, 14,  3,  9]])

In [30]:
data = np.random.random((10,4))
data

array([[0.07736429, 0.17251197, 0.68132126, 0.34670346],
       [0.72802974, 0.43738999, 0.68583818, 0.92117072],
       [0.90034704, 0.21894986, 0.84493529, 0.01536689],
       [0.98099045, 0.40834876, 0.64795831, 0.30621017],
       [0.935176  , 0.06767965, 0.86720328, 0.76762147],
       [0.75148326, 0.52615986, 0.76959318, 0.15365949],
       [0.91357457, 0.37325691, 0.12944615, 0.28189219],
       [0.14403719, 0.18747771, 0.9705933 , 0.2031553 ],
       [0.93114372, 0.55790975, 0.34332766, 0.21901737],
       [0.1371063 , 0.89802195, 0.01740915, 0.38546459]])

In [33]:
data = np.random.rand()
data

0.6383753031867107

In [195]:
x[0:-1]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [197]:
x[[0,-1],::,::]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [225]:
x[[0,-1],0:1:,::]

array([[[ 0,  1,  2,  3]],

       [[24, 25, 26, 27]]])

In [229]:
x[[0,-1],[0,2],1:3:]

array([[ 1,  2],
       [33, 34]])

In [204]:
x[[0,-1],0:1:,1:3:]

array([[[ 1,  2]],

       [[25, 26]]])

In [205]:
x[[0,-1],0:1:,::2]

array([[[ 0,  2]],

       [[24, 26]]])

In [213]:
x[0::2,0:1:,::2]

array([[[ 0,  2]],

       [[24, 26]]])

In [166]:
x[x%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [168]:
np.asarray([1,2,3])

array([1, 2, 3])

In [173]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [5]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [176]:
np.ones_like(x)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
ndata = np.arange(1,21)
display(ndata)

display(ndata.min())
display(ndata.max())
display(ndata.argmax())
display(ndata.argmin())
display(ndata.mean())
display(ndata.std())
display(ndata.sum())
display(ndata.cumsum())

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

np.int64(1)

np.int64(20)

np.int64(19)

np.int64(0)

np.float64(10.5)

np.float64(5.766281297335398)

np.int64(210)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210])